
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.REGISTRY_USER }}/portfolio:${{ github.run_number }} \
            -t ${{ secrets.REGISTRY_USER }}/portfolio .

      - name: Login to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_USER }}/portfolio:${{ github.run_number }}
          docker push ${{ secrets.REGISTRY_USER }}/portfolio
